language: node_js
node_js: node
script:
 - npm test
 - npm run lint
deploy:
  provider: firebase
  on:
    branch: develop
  token:
    secure: "PyTDSQilivgcxqKF2ek9wf9Ajvazm/bpfozTdlCapd5qoUdC/boiJX9CLGbSjXdkE2WHJbtam/CG+sqqdIfjS3tnV6+9UHOp5CZvonxN4Z5Q+PlJxY8Upwxgnz6fbwR6v41MM7sX1l0LunTPoP4mJnHnrLY1gDL4uxOAM8yyirRgktHF9QggkwRSlm2lNxXmFbrXMFp2dAjN9AquIz8KZNuDsfXkhUFBasVlybq/coaEy1EceaOJlrx4MzEGirTxESVCsT5F3UDN758IuoToCBgqAsyyogzS3orvqHw3QwNEx1QKX6un4cUS5+wnS4/sBKSySbjJijMve4MIL1bSipVXmQPnlWtKsK22K7OQCmRRK9Cmse+rffdcD9/H47zOvr/9k1dELeKsdBjI62UAUqH3+ybpgDhGUFaL13/MGJmmMzxmQyGdEIKpJERiAlSgpC58329HPhzEm5Pw+EEeKIRnEFDICWra+o6CZMnhyvZpD1cJgGyMNk5lrlWagjTO3xSJTq0LzUzACIm+fZBJ5IQZ6RDQI350RGNDhcLqFoN7IgOjuUryPDRxHDVtmnqtKwYAoxBqcDhMSxAd0j99XRY07fdo1tir+Wzf5pQGXckk7pd7h7fE8QjPEJjq690Pec0Q+6xL6yZAthMnxgjnSMT9wphHJ2eG89sZ65d/5cI="
cache: yarn
